# -- config path
config_dir : 'swin'
config_file : 'upernet_swin_large_patch4_window12_512x512_80k_coco_pretrain_384x384_22K'

# -- checkpoint
ckpt_name : 'latest'

# -- save csv name
csv_name : 'submission'